### ISSUE TITLE
Support exclusion lists

### ISSUE THREAD

**Issue by cjohansson** [cjohansson/emacs-ssh-deploy#19]
Simply a variable which holds paths to exclude or syncing

**Comment by PrestanceDesign** [comment]
Hi ! Yeah like `.git/` directory, etc because each time I commit with magit, I have this warning :
```
Warning (ssh-deploy): External file has '/ssh:user@server.fr/.git/COMMIT_EDITMSG' changed, please download or diff
```

**Comment by PrestanceDesign** [comment]
Hi @cjohansson !

Nice, I just updated my Spacemacs packages and I had notice there is a new version of ssh-deploy with the new exclusion feature https://github.com/cjohansson/emacs-ssh-deploy/commit/4c1a539e6f95e4847c13685d2b752e40d2b8aad8 !

I will tried that, thank you !

**Comment by cjohansson** [comment]
Yes, I tried it for a while yesterday and it seems to do the trick. Let me know if you find any issues with it. 👍
