### ISSUE TITLE
'display-warning throws 'wrong-type-argument error

### ISSUE THREAD

**Issue by articuluxe** [cjohansson/emacs-ssh-deploy#39]
When something goes wrong, ssh-deploy is calling 'display-warning with a string, instead of a symbol, as its first argument.  I had to change it to the symbol 'ssh-deploy rather than "ssh-deploy".
```
Debugger entered--Lisp error: (wrong-type-argument listp "ssh-deploy")
  warning-suppress-p("ssh-deploy" ((undo discard-info)))
  display-warning("ssh-deploy" "This is a warning")
```
I am running emacs 24 and 25.

**Comment by cjohansson** [comment]
Ah, I haven’t stumbled upon that. Do you know if Emacs 26 and 27 supports using a symbol? I probably does, since it should be backwards compatible. 
You can open a pull request for this if you want.

**Comment by cjohansson** [comment]
I made a commit for it now, hope it resolves the issue for you

**Comment by articuluxe** [comment]
Looks much better thank you, and thanks for the package.
