### ISSUE TITLE
termux emacs async method support issue

### ISSUE THREAD

**Issue by bokuno** [cjohansson/emacs-ssh-deploy#56]
When I was using emacs(26.1) in Termux, I found ssh-deploy could not use 'make-thread'.
The warning output is:
Warning (ssh-deploy): Neither make-thread nor async-start functions are available!
But this emacs does have 'make-thread':
make-thread is a built-in function in ‘C source code’.
And elisp code like 
'(make-thread(lambda()(sleep-for 5)(message "worked!")))' 
really worked.

**Comment by cjohansson** [comment]
Ah seems to be a bug in the logic there, if you set `(setq ssh-deploy-async-with-threads 1)` it should work.

```
(if (and (fboundp 'make-thread)
           async-with-threads
           (> async-with-threads 0))
(progn ...)
(if (fboundp 'async-start)
    (progn ....)
(display-warning 'ssh-deploy "Neither make-thread nor async-start functions are available!"))))
```

**Comment by cjohansson** [comment]
The error message should be improved in [this commit](https://github.com/cjohansson/emacs-ssh-deploy/commit/664f52c264801653eabaad015cbed011a8e191cd)
