### ISSUE TITLE
New feature idea? dired ediff ignore files on server

### ISSUE THREAD

**Issue by jeswcollins** [cjohansson/emacs-ssh-deploy#62]
I like working on the server for rapid UI bug fix and new feature experiments. I've generated new files on the server. I would like to keep these there, but don't want them to show up in the SSH Deploy dired ediff buffer. 

Is there a preferred way to go about implementing such a feature, if it doesn't already exist?

**Comment by jeswcollins** [comment]
Maybe I didn't do enough research before I asked this question. I see that I may be able to set `dired-omit-mode` to `t` e.g. in https://www.gnu.org/software/emacs/manual/html_node/dired-x/Omitting-Variables.html for this feature idea.

**Comment by jeswcollins** [comment]
I tried the above, but my ediffs seem to not have changed.
```
 (dired-mode . (
		(dired-omit-mode . t)
		;;(dired-omit-files "^#\\|\\.$\\|~|-err")
		)

  )```

**Comment by jeswcollins** [comment]
Ah I see also `ssh-deploy-exclude-list`
https://github.com/cjohansson/emacs-ssh-deploy/blob/d0f7294d23380766dcabdb4ed21bc6a68e496110/ssh-deploy.el#L211
Seems likely that this issue can be closed, but I will try to see if I can set this variable first

**Comment by cjohansson** [comment]
I'm not sure what kind of feature you want but the `ssh-deploy-exclude-list` will exclude files when doing recursive directory differences both from local and from remote host

**Comment by jeswcollins** [comment]
Should I be able to add to `ssh-deploy-exclude-list` from .dir-locals.el?

I tried adding `  (setq list1 '("path/to/file_to_be_excluded.txt"))
  (add_to_list 'ssh-deploy-exclude-list 'list1)
` but doesn't seem to change variable according to `C-h v ssh-deploy-exclude-list`.

**Comment by jeswcollins** [comment]
I wasn't modifying my .dir-locals.el properly. 

Reading this link on Directory Variables helped:
https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html#Directory-Variables

The line I added was:

```(ssh-deploy-exclude-list . ("path/to/file_to_exclude_1.txt" ".git/" ".dir-locals.el"))
 ```

Will close the issue.
