### ISSUE TITLE
Problems with uploading project directory

### ISSUE THREAD

**Issue by WhatDothLife** [cjohansson/emacs-ssh-deploy#66]
I can't upload my project dir to the remote.

### Setup of .dir-locals.el:

```
((nil . (
  (ssh-deploy-root-local . "/home/respighi/projects/DeepHPM")
  (ssh-deploy-root-remote . "/sftp:s8179597@taurus.hrsk.tu-dresden.de:/home/h6/s8179597/DeepHPM/")
  (ssh-deploy-async . 1)
  (ssh-deploy-on-explicit-save . 1)
)))
```

### Problem 
When I call `ssh-deploy-upload-handler` the echo area shows  `Uploading file ’/home/respighi/projects/DeepHPM/Schrodinger2D_DeepHPM.py’ to ’/Schrodinger2D_DeepHPM.py’.. (asynchronously)`

After this message the minibuffer stays silent. The file doesn't change on the remote.
 I also find it suspicious that for the remote only the relative path is shown. 

### More info
I'm using doom-emacs' upload module. The config-file can be found [here](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/upload/config.el).

<details><pre>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Sep 16, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64
        path       (~/.cargo/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu)
config  envfile    nil
        elc-files  0
        
```
</pre></details>

Any idea how to fix this?

**Comment by cjohansson** [comment]
Yes, I suspect an issue occurs asynchronously, turn off asynchronous mode with ’(setq ssh-deploy-async 0)’ while in the dired buffer and try again.

Other thing is that emacs have poor platform support for sftp, if the conmection is just FTP over SSH then try using SSH instead as protocol

**Comment by WhatDothLife** [comment]
I enabled asynchronous deployment in the first place, because synchronous deployment resulted in an error message. it reads as follows:
```
Uploading file ’/home/michael/projects/DeepHPM/Schrodinger2D_DeepHPM.py’ to ’/Schrodinger2D_DeepHPM.py’.. (synchronously)
ssh-deploy--upload-via-tramp: Opening output file: Permission denied, /Schrodinger2D_DeepHPM.py
```
Might this be due to the remote configuration?

**Comment by cjohansson** [comment]
Sounds like you lack permission on the remote host. Probably server configuration issue unless yor remote path is wrong

**Comment by cjohansson** [comment]
I changed by mind the expected message should be

```
Uploading file ’/home/michael/projects/DeepHPM/Schrodinger2D_DeepHPM.py’ to ’/sftp:s8179597@taurus.hrsk.tu-dresden.de:/home/h6/s8179597/DeepHPM/Schrodinger2D_DeepHPM.py’.. (synchronously)
```

I think doom is using a fork from this project, maybe it's using a different message. Anyway if your using the latest version of ssh-deploy your message should be as above, otherwise something is wrong with your paths.

**Comment by cjohansson** [comment]
I'm closing this since you're not answering my questions, please re-open if issue persists
