### ISSUE TITLE
Need add a option use force-upload on save

### ISSUE THREAD

**Issue by vaxilicaihouxian** [cjohansson/emacs-ssh-deploy#67]
I know there is an option like this:

> (ssh-deploy-on-explicit-save 1)

I need an option like that but with force parameter.
May be `ssh-deploy-force-on-explicit-save`.
Can you add this feature?
Thx!

**Comment by cjohansson** [comment]
Sure, I'll add it soon

**Comment by vaxilicaihouxian** [comment]
> Sure, I'll add it soon

Thx.

**Comment by cjohansson** [comment]
Added in [this commit](https://github.com/cjohansson/emacs-ssh-deploy/commit/1bb2f821d4a78d483c147759348a29531486cdc4) you just need to set the variable `ssh-deploy-force-on-explicit-save` to `1` globally, per-directory or per-file

**Comment by vaxilicaihouxian** [comment]
> Added in [this commit](https://github.com/cjohansson/emacs-ssh-deploy/commit/1bb2f821d4a78d483c147759348a29531486cdc4) you just need to set the variable `ssh-deploy-force-on-explicit-save` to `1` globally, per-directory or per-file

Awesome!
