### ISSUE TITLE
Fails to target remote system, tries to "deploy" on /

### ISSUE THREAD

**Issue by fdgonthier** [cjohansson/emacs-ssh-deploy#71]
I've configured emacs-ssh-deploy this way:

```lisp
((nil . ((ssh-deploy-root-local . "/home/neumann/project")
         (ssh-deploy-root-remote . "/ssh:neumann@remote:/home/neumann/project")
         (ssh-deploy-automatically-detect-remote-changes . 0)
         (ssh-deploy-on-explicit-save . 1)
         (ssh-deploy-debug . 1)
         (ssh-deploy-verbose . 1)
         (ssh-deploy-async . 0)
)))
```

Unfortunately, whenever I save, or try to force the upload, it seems the addon tries to access my root directory instead of the remote system.

I've traced _ssh-deploy--get-relative-path_ and it seems to strip the remote path entirely:

```
======================================================================
1 -> (ssh-deploy--get-relative-path "/home/neumann/project" "/home/neumann/project/file")
1 <- ssh-deploy--get-relative-path: "/file"
```

Output tracing _expand-file-name_ may also help, although I'm not sure how to interpret ikt.

```
1 -> (expand-file-name "/file" "/ssh:neumann@remote:/home/neumann/project")
| 2 -> (expand-file-name "/file" "/ssh:neumann@remote:/home/neumann/project")
| 2 <- expand-file-name: "/file"
1 <- expand-file-name: "/file"
```

This is as far as I can go for now. Not very familiar with Emacs development.

**Comment by cjohansson** [comment]
The issue, I think, is the paths should be ending with a front-slash, so replace "/bla/bla" with "/bla/bla/"

**Comment by fdgonthier** [comment]
... it's working right now... I really thought I had tried this. Really sorry. *Shame*
